create table if not exists public.record_alarm_rules (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    log_type text not null check (log_type in ('FEEDING','SLEEP','GROWTH','MOMENT','MEDICINE','CHECKLIST','DIAPER','TEMPERATURE','PUMPING','MEMO')),
    enabled boolean not null default false,
    interval_minutes integer not null default 180 check (interval_minutes between 5 and 43200),
    notify_scope text not null default 'FAMILY' check (notify_scope in ('SELF','FAMILY')),
    updated_by_id bigint references public.caregivers(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (family_id, log_type)
);

create table if not exists public.record_alarm_schedules (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint references public.children(id) on delete cascade,
    source_log_id bigint references public.logs(id) on delete cascade,
    log_type text not null check (log_type in ('FEEDING','SLEEP','GROWTH','MOMENT','MEDICINE','CHECKLIST','DIAPER','TEMPERATURE','PUMPING','MEMO')),
    interval_minutes integer not null check (interval_minutes between 5 and 43200),
    scheduled_for timestamptz not null,
    status text not null default 'SCHEDULED' check (status in ('SCHEDULED','FIRED','SNOOZED','DISMISSED','CANCELLED')),
    notify_scope text not null default 'FAMILY' check (notify_scope in ('SELF','FAMILY')),
    created_by_id bigint references public.caregivers(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source_log_id)
);

create index if not exists idx_record_alarm_rules_family_type on public.record_alarm_rules(family_id, log_type);
create index if not exists idx_record_alarm_schedules_family_status_time on public.record_alarm_schedules(family_id, status, scheduled_for);
create index if not exists idx_record_alarm_schedules_log on public.record_alarm_schedules(source_log_id);

drop trigger if exists record_alarm_rules_touch_updated_at on public.record_alarm_rules;
create trigger record_alarm_rules_touch_updated_at before update on public.record_alarm_rules for each row execute function public.touch_updated_at();

drop trigger if exists record_alarm_schedules_touch_updated_at on public.record_alarm_schedules;
create trigger record_alarm_schedules_touch_updated_at before update on public.record_alarm_schedules for each row execute function public.touch_updated_at();

alter table public.record_alarm_rules enable row level security;
alter table public.record_alarm_schedules enable row level security;

drop policy if exists record_alarm_rules_select_member on public.record_alarm_rules;
create policy record_alarm_rules_select_member on public.record_alarm_rules
    for select to authenticated
    using (public.is_family_member(family_id));

drop policy if exists record_alarm_rules_upsert_member on public.record_alarm_rules;
create policy record_alarm_rules_upsert_member on public.record_alarm_rules
    for all to authenticated
    using (public.is_family_member(family_id))
    with check (public.is_family_member(family_id));

drop policy if exists record_alarm_schedules_select_member on public.record_alarm_schedules;
create policy record_alarm_schedules_select_member on public.record_alarm_schedules
    for select to authenticated
    using (public.is_family_member(family_id));

drop policy if exists record_alarm_schedules_insert_member on public.record_alarm_schedules;
create policy record_alarm_schedules_insert_member on public.record_alarm_schedules
    for insert to authenticated
    with check (
        public.is_family_member(family_id)
        and (created_by_id is null or created_by_id = public.current_caregiver_id())
    );

drop policy if exists record_alarm_schedules_update_member on public.record_alarm_schedules;
create policy record_alarm_schedules_update_member on public.record_alarm_schedules
    for update to authenticated
    using (public.is_family_member(family_id))
    with check (public.is_family_member(family_id));

grant select, insert, update, delete on public.record_alarm_rules to authenticated;
grant select, insert, update on public.record_alarm_schedules to authenticated;
grant usage, select on sequence public.record_alarm_rules_id_seq to authenticated;
grant usage, select on sequence public.record_alarm_schedules_id_seq to authenticated;

create or replace function public.default_record_alarm_minutes(p_type text)
returns integer
language sql
immutable
set search_path = public
as $$
    select case p_type
        when 'FEEDING' then 180
        when 'PUMPING' then 180
        when 'MEDICINE' then 480
        when 'SLEEP' then 120
        when 'DIAPER' then 240
        when 'TEMPERATURE' then 30
        when 'GROWTH' then 10080
        else 180
    end;
$$;

create or replace function public.upsert_record_alarm_rule_checked(
    p_family_id bigint,
    p_log_type text,
    p_enabled boolean,
    p_interval_minutes integer,
    p_notify_scope text default 'FAMILY'
)
returns public.record_alarm_rules
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_rule public.record_alarm_rules%rowtype;
    v_log_type text := upper(trim(coalesce(p_log_type, '')));
    v_notify_scope text := upper(trim(coalesce(p_notify_scope, 'FAMILY')));
    v_interval integer := coalesce(p_interval_minutes, public.default_record_alarm_minutes(upper(trim(coalesce(p_log_type, '')))));
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_log_type not in ('FEEDING','SLEEP','GROWTH','MOMENT','MEDICINE','CHECKLIST','DIAPER','TEMPERATURE','PUMPING','MEMO') then raise exception 'Invalid log type'; end if;
    if v_notify_scope not in ('SELF','FAMILY') then raise exception 'Invalid notify scope'; end if;
    if v_interval < 5 or v_interval > 43200 then raise exception 'Record alarm interval must be between 5 and 43200 minutes'; end if;

    insert into public.record_alarm_rules(family_id, log_type, enabled, interval_minutes, notify_scope, updated_by_id)
    values (p_family_id, v_log_type, coalesce(p_enabled, false), v_interval, v_notify_scope, v_current.id)
    on conflict (family_id, log_type) do update set
        enabled = excluded.enabled,
        interval_minutes = excluded.interval_minutes,
        notify_scope = excluded.notify_scope,
        updated_by_id = excluded.updated_by_id,
        updated_at = now()
    returning * into v_rule;

    return v_rule;
end;
$$;

create or replace function public.schedule_record_alarm_checked(
    p_family_id bigint,
    p_child_id bigint,
    p_source_log_id bigint,
    p_log_type text,
    p_recorded_at timestamptz,
    p_interval_minutes integer,
    p_notify_scope text default 'FAMILY'
)
returns public.record_alarm_schedules
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_log public.logs%rowtype;
    v_schedule public.record_alarm_schedules%rowtype;
    v_log_type text := upper(trim(coalesce(p_log_type, '')));
    v_notify_scope text := upper(trim(coalesce(p_notify_scope, 'FAMILY')));
    v_interval integer := coalesce(p_interval_minutes, public.default_record_alarm_minutes(upper(trim(coalesce(p_log_type, '')))));
    v_recorded_at timestamptz := coalesce(p_recorded_at, now());
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_log_type not in ('FEEDING','SLEEP','GROWTH','MOMENT','MEDICINE','CHECKLIST','DIAPER','TEMPERATURE','PUMPING','MEMO') then raise exception 'Invalid log type'; end if;
    if v_notify_scope not in ('SELF','FAMILY') then raise exception 'Invalid notify scope'; end if;
    if v_interval < 5 or v_interval > 43200 then raise exception 'Record alarm interval must be between 5 and 43200 minutes'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);

    if p_source_log_id is not null then
        select * into v_log
        from public.logs
        where id = p_source_log_id
          and family_id = p_family_id
        limit 1;

        if not found then raise exception 'Source log was not found'; end if;
        v_recorded_at := coalesce(v_log.recorded_at, v_recorded_at);
        v_log_type := v_log.type;
    end if;

    insert into public.record_alarm_schedules(
        family_id,
        child_id,
        source_log_id,
        log_type,
        interval_minutes,
        scheduled_for,
        notify_scope,
        created_by_id
    ) values (
        p_family_id,
        v_child.id,
        p_source_log_id,
        v_log_type,
        v_interval,
        v_recorded_at + make_interval(mins => v_interval),
        v_notify_scope,
        v_current.id
    )
    on conflict (source_log_id) do update set
        interval_minutes = excluded.interval_minutes,
        scheduled_for = excluded.scheduled_for,
        status = 'SCHEDULED',
        notify_scope = excluded.notify_scope,
        updated_at = now()
    returning * into v_schedule;

    return v_schedule;
end;
$$;

revoke all on function public.default_record_alarm_minutes(text) from public, anon;
revoke all on function public.upsert_record_alarm_rule_checked(bigint, text, boolean, integer, text) from public, anon;
revoke all on function public.schedule_record_alarm_checked(bigint, bigint, bigint, text, timestamptz, integer, text) from public, anon;

grant execute on function public.default_record_alarm_minutes(text) to authenticated;
grant execute on function public.upsert_record_alarm_rule_checked(bigint, text, boolean, integer, text) to authenticated;
grant execute on function public.schedule_record_alarm_checked(bigint, bigint, bigint, text, timestamptz, integer, text) to authenticated;

insert into public.record_alarm_rules(family_id, log_type, enabled, interval_minutes, notify_scope)
select families.id, defaults.log_type, false, public.default_record_alarm_minutes(defaults.log_type), 'FAMILY'
from public.families
cross join (
    values
        ('FEEDING'),
        ('SLEEP'),
        ('DIAPER'),
        ('TEMPERATURE'),
        ('MEDICINE'),
        ('PUMPING')
) as defaults(log_type)
on conflict (family_id, log_type) do nothing;
