-- Data contracts for the 01-35 UI specification.
-- This migration keeps the existing Supabase-only architecture and extends it
-- with typed, family-scoped records required by the detailed spec screens.

alter table public.logs
    add column if not exists details jsonb not null default '{}'::jsonb,
    add column if not exists recorded_end_at timestamptz,
    add column if not exists record_subtype text;

alter table public.logs drop constraint if exists logs_type_check;
alter table public.logs
    add constraint logs_type_check check (
        type in (
            'FEEDING',
            'SLEEP',
            'GROWTH',
            'MOMENT',
            'MEDICINE',
            'CHECKLIST',
            'DIAPER',
            'TEMPERATURE',
            'PUMPING',
            'MEMO'
        )
    );

create index if not exists idx_logs_family_type_recorded on public.logs(family_id, type, recorded_at desc);
create index if not exists idx_logs_details_gin on public.logs using gin(details);

drop policy if exists logs_delete_own on public.logs;
create policy logs_delete_own on public.logs for delete to authenticated using (
    caregiver_id = public.current_caregiver_id()
);

grant update, delete on public.logs to authenticated;

drop policy if exists children_update_member on public.children;
create policy children_update_member on public.children for update to authenticated using (public.is_family_member(family_id)) with check (public.is_family_member(family_id));

grant update on public.children to authenticated;

create table if not exists public.record_attachments (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint references public.children(id) on delete set null,
    log_id bigint references public.logs(id) on delete cascade,
    memory_entry_id bigint references public.memory_entries(id) on delete cascade,
    created_by_id bigint references public.caregivers(id) on delete set null,
    image_url text not null,
    caption text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint record_attachments_owner_check check (log_id is not null or memory_entry_id is not null)
);

create table if not exists public.growth_measurements (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint not null references public.children(id) on delete cascade,
    caregiver_id bigint references public.caregivers(id) on delete set null,
    measured_at timestamptz not null,
    height_cm numeric(6,2),
    weight_kg numeric(6,2),
    head_circumference_cm numeric(6,2),
    note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint growth_measurements_has_value check (
        height_cm is not null or weight_kg is not null or head_circumference_cm is not null
    )
);

create table if not exists public.notification_preferences (
    family_id bigint primary key references public.families(id) on delete cascade,
    feeding_enabled boolean not null default true,
    medicine_enabled boolean not null default true,
    vaccination_enabled boolean not null default true,
    growth_enabled boolean not null default false,
    briefing_enabled boolean not null default true,
    health_alerts_enabled boolean not null default true,
    daily_time time not null default time '08:00',
    updated_by_id bigint references public.caregivers(id) on delete set null,
    updated_at timestamptz not null default now()
);

create table if not exists public.family_invitations (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    email text not null,
    relationship text not null,
    note text,
    status text not null default 'PENDING' check (status in ('PENDING', 'ACCEPTED', 'CANCELLED', 'EXPIRED')),
    invited_by_id bigint references public.caregivers(id) on delete set null,
    created_at timestamptz not null default now(),
    accepted_at timestamptz
);

create table if not exists public.vaccination_records (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint not null references public.children(id) on delete cascade,
    name text not null,
    dose_label text,
    status text not null default 'SCHEDULED' check (status in ('SCHEDULED', 'COMPLETED', 'SKIPPED')),
    due_at timestamptz not null,
    completed_at timestamptz,
    note text,
    created_by_id bigint references public.caregivers(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.hospital_visits (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint not null references public.children(id) on delete cascade,
    hospital_name text not null,
    reason text,
    visited_at timestamptz not null,
    diagnosis text,
    note text,
    created_by_id bigint references public.caregivers(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.export_jobs (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    requested_by_id bigint references public.caregivers(id) on delete set null,
    format text not null check (format in ('PDF', 'EXCEL', 'CSV')),
    sections jsonb not null default '[]'::jsonb,
    status text not null default 'REQUESTED' check (status in ('REQUESTED', 'PROCESSING', 'READY', 'FAILED')),
    requested_at timestamptz not null default now(),
    completed_at timestamptz,
    download_url text,
    error_message text
);

create index if not exists idx_record_attachments_family_created on public.record_attachments(family_id, created_at desc);
create index if not exists idx_record_attachments_log on public.record_attachments(log_id);
create index if not exists idx_growth_measurements_child_measured on public.growth_measurements(child_id, measured_at desc);
create index if not exists idx_family_invitations_family_created on public.family_invitations(family_id, created_at desc);
create index if not exists idx_vaccination_records_family_due on public.vaccination_records(family_id, due_at);
create index if not exists idx_hospital_visits_family_visited on public.hospital_visits(family_id, visited_at desc);
create index if not exists idx_export_jobs_family_requested on public.export_jobs(family_id, requested_at desc);

drop trigger if exists record_attachments_touch_updated_at on public.record_attachments;
create trigger record_attachments_touch_updated_at before update on public.record_attachments for each row execute function public.touch_updated_at();
drop trigger if exists growth_measurements_touch_updated_at on public.growth_measurements;
create trigger growth_measurements_touch_updated_at before update on public.growth_measurements for each row execute function public.touch_updated_at();
drop trigger if exists vaccination_records_touch_updated_at on public.vaccination_records;
create trigger vaccination_records_touch_updated_at before update on public.vaccination_records for each row execute function public.touch_updated_at();
drop trigger if exists hospital_visits_touch_updated_at on public.hospital_visits;
create trigger hospital_visits_touch_updated_at before update on public.hospital_visits for each row execute function public.touch_updated_at();

alter table public.record_attachments enable row level security;
alter table public.growth_measurements enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.family_invitations enable row level security;
alter table public.vaccination_records enable row level security;
alter table public.hospital_visits enable row level security;
alter table public.export_jobs enable row level security;

drop policy if exists record_attachments_select_member on public.record_attachments;
create policy record_attachments_select_member on public.record_attachments for select to authenticated using (public.is_family_member(family_id));
drop policy if exists record_attachments_insert_member on public.record_attachments;
create policy record_attachments_insert_member on public.record_attachments for insert to authenticated with check (
    public.is_family_member(family_id)
    and (created_by_id is null or created_by_id = public.current_caregiver_id())
);
drop policy if exists record_attachments_update_own on public.record_attachments;
create policy record_attachments_update_own on public.record_attachments for update to authenticated using (
    created_by_id = public.current_caregiver_id()
) with check (
    public.is_family_member(family_id)
    and (created_by_id is null or created_by_id = public.current_caregiver_id())
);
drop policy if exists record_attachments_delete_own on public.record_attachments;
create policy record_attachments_delete_own on public.record_attachments for delete to authenticated using (
    created_by_id = public.current_caregiver_id()
);

drop policy if exists growth_measurements_select_member on public.growth_measurements;
create policy growth_measurements_select_member on public.growth_measurements for select to authenticated using (public.is_family_member(family_id));
drop policy if exists growth_measurements_insert_member on public.growth_measurements;
create policy growth_measurements_insert_member on public.growth_measurements for insert to authenticated with check (
    public.is_family_member(family_id)
    and (caregiver_id is null or caregiver_id = public.current_caregiver_id())
);
drop policy if exists growth_measurements_update_own on public.growth_measurements;
create policy growth_measurements_update_own on public.growth_measurements for update to authenticated using (
    caregiver_id = public.current_caregiver_id()
) with check (
    public.is_family_member(family_id)
    and (caregiver_id is null or caregiver_id = public.current_caregiver_id())
);

drop policy if exists notification_preferences_select_member on public.notification_preferences;
create policy notification_preferences_select_member on public.notification_preferences for select to authenticated using (public.is_family_member(family_id));
drop policy if exists notification_preferences_upsert_member on public.notification_preferences;
create policy notification_preferences_upsert_member on public.notification_preferences for all to authenticated using (public.is_family_member(family_id)) with check (public.is_family_member(family_id));

drop policy if exists family_invitations_select_member on public.family_invitations;
create policy family_invitations_select_member on public.family_invitations for select to authenticated using (public.is_family_member(family_id));
drop policy if exists family_invitations_insert_member on public.family_invitations;
create policy family_invitations_insert_member on public.family_invitations for insert to authenticated with check (
    public.is_family_member(family_id)
    and (invited_by_id is null or invited_by_id = public.current_caregiver_id())
);
drop policy if exists family_invitations_update_member on public.family_invitations;
create policy family_invitations_update_member on public.family_invitations for update to authenticated using (public.is_family_member(family_id)) with check (public.is_family_member(family_id));

drop policy if exists vaccination_records_select_member on public.vaccination_records;
create policy vaccination_records_select_member on public.vaccination_records for select to authenticated using (public.is_family_member(family_id));
drop policy if exists vaccination_records_insert_member on public.vaccination_records;
create policy vaccination_records_insert_member on public.vaccination_records for insert to authenticated with check (
    public.is_family_member(family_id)
    and (created_by_id is null or created_by_id = public.current_caregiver_id())
);
drop policy if exists vaccination_records_update_member on public.vaccination_records;
create policy vaccination_records_update_member on public.vaccination_records for update to authenticated using (public.is_family_member(family_id)) with check (public.is_family_member(family_id));

drop policy if exists hospital_visits_select_member on public.hospital_visits;
create policy hospital_visits_select_member on public.hospital_visits for select to authenticated using (public.is_family_member(family_id));
drop policy if exists hospital_visits_insert_member on public.hospital_visits;
create policy hospital_visits_insert_member on public.hospital_visits for insert to authenticated with check (
    public.is_family_member(family_id)
    and (created_by_id is null or created_by_id = public.current_caregiver_id())
);
drop policy if exists hospital_visits_update_member on public.hospital_visits;
create policy hospital_visits_update_member on public.hospital_visits for update to authenticated using (public.is_family_member(family_id)) with check (public.is_family_member(family_id));

drop policy if exists export_jobs_select_member on public.export_jobs;
create policy export_jobs_select_member on public.export_jobs for select to authenticated using (public.is_family_member(family_id));
drop policy if exists export_jobs_insert_member on public.export_jobs;
create policy export_jobs_insert_member on public.export_jobs for insert to authenticated with check (
    public.is_family_member(family_id)
    and (requested_by_id is null or requested_by_id = public.current_caregiver_id())
);

revoke all on
    public.record_attachments,
    public.growth_measurements,
    public.notification_preferences,
    public.family_invitations,
    public.vaccination_records,
    public.hospital_visits,
    public.export_jobs
from anon, public;

grant select, insert, update, delete on
    public.record_attachments,
    public.growth_measurements,
    public.family_invitations,
    public.vaccination_records,
    public.hospital_visits
to authenticated;
grant select, insert, update on public.notification_preferences to authenticated;
grant select, insert on public.export_jobs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.care_record_label(p_type text)
returns text
language sql
stable
set search_path = public
as $$
    select case p_type
        when 'FEEDING' then '수유'
        when 'SLEEP' then '수면'
        when 'DIAPER' then '배변'
        when 'TEMPERATURE' then '체온'
        when 'MEDICINE' then '복약'
        when 'PUMPING' then '유축'
        when 'MEMO' then '메모'
        when 'MOMENT' then '순간'
        when 'GROWTH' then '성장'
        when 'CHECKLIST' then '체크리스트'
        else '생활'
    end
$$;

create or replace function public.create_care_record_with_chat(
    p_family_id bigint,
    p_child_id bigint,
    p_type text,
    p_value text,
    p_note text,
    p_recorded_at timestamptz,
    p_recorded_end_at timestamptz default null,
    p_record_subtype text default null,
    p_details jsonb default '{}'::jsonb
)
returns public.logs
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_log public.logs%rowtype;
    v_value text := trim(coalesce(p_value, ''));
    v_details jsonb := coalesce(p_details, '{}'::jsonb);
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if p_type not in ('FEEDING','SLEEP','GROWTH','MOMENT','MEDICINE','CHECKLIST','DIAPER','TEMPERATURE','PUMPING','MEMO') then raise exception 'Invalid log type'; end if;
    if v_value = '' then raise exception 'Log value is required'; end if;
    if p_recorded_at is null then raise exception 'Recorded time is required'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);

    insert into public.logs(family_id, child_id, caregiver_id, type, entry_value, note, recorded_at, recorded_end_at, record_subtype, details)
    values (
        p_family_id,
        v_child.id,
        v_current.id,
        p_type,
        v_value,
        nullif(trim(coalesce(p_note, '')), ''),
        p_recorded_at,
        p_recorded_end_at,
        nullif(trim(coalesce(p_record_subtype, '')), ''),
        v_details
    )
    returning * into v_log;

    insert into public.chat_messages(family_id, sender_id, body, message_type)
    values (p_family_id, v_current.id, format('%s 기록을 남겼어요: %s', public.care_record_label(v_log.type), v_log.entry_value), 'LOG_UPDATE');

    return v_log;
end;
$$;

create or replace function public.update_care_record_checked(
    p_log_id bigint,
    p_value text,
    p_note text,
    p_recorded_at timestamptz,
    p_recorded_end_at timestamptz default null,
    p_record_subtype text default null,
    p_details jsonb default '{}'::jsonb
)
returns public.logs
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_log public.logs%rowtype;
    v_value text := trim(coalesce(p_value, ''));
begin
    v_current := public.current_caregiver();
    if v_value = '' then raise exception 'Log value is required'; end if;
    if p_recorded_at is null then raise exception 'Recorded time is required'; end if;

    update public.logs
    set entry_value = v_value,
        note = nullif(trim(coalesce(p_note, '')), ''),
        recorded_at = p_recorded_at,
        recorded_end_at = p_recorded_end_at,
        record_subtype = nullif(trim(coalesce(p_record_subtype, '')), ''),
        details = coalesce(p_details, '{}'::jsonb),
        updated_at = now()
    where id = p_log_id
      and family_id = v_current.family_id
      and caregiver_id = v_current.id
    returning * into v_log;

    if not found then raise exception 'Care record was not found'; end if;
    return v_log;
end;
$$;

create or replace function public.delete_care_record_checked(p_log_id bigint)
returns bigint
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
begin
    v_current := public.current_caregiver();

    delete from public.logs
    where id = p_log_id
      and family_id = v_current.family_id
      and caregiver_id = v_current.id;

    if not found then raise exception 'Care record was not found'; end if;
    return p_log_id;
end;
$$;

create or replace function public.create_growth_measurement_checked(
    p_family_id bigint,
    p_child_id bigint,
    p_measured_at timestamptz,
    p_height_cm numeric,
    p_weight_kg numeric,
    p_head_circumference_cm numeric,
    p_note text
)
returns public.growth_measurements
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_growth public.growth_measurements%rowtype;
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if p_measured_at is null then raise exception 'Measured time is required'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);

    insert into public.growth_measurements(
        family_id,
        child_id,
        caregiver_id,
        measured_at,
        height_cm,
        weight_kg,
        head_circumference_cm,
        note
    ) values (
        p_family_id,
        v_child.id,
        v_current.id,
        p_measured_at,
        p_height_cm,
        p_weight_kg,
        p_head_circumference_cm,
        nullif(trim(coalesce(p_note, '')), '')
    )
    returning * into v_growth;

    insert into public.chat_messages(family_id, sender_id, body, message_type)
    values (p_family_id, v_current.id, '성장 기록을 남겼어요.', 'LOG_UPDATE');

    return v_growth;
end;
$$;

create or replace function public.upsert_notification_preferences_checked(
    p_family_id bigint,
    p_feeding_enabled boolean,
    p_medicine_enabled boolean,
    p_vaccination_enabled boolean,
    p_growth_enabled boolean,
    p_briefing_enabled boolean,
    p_health_alerts_enabled boolean,
    p_daily_time time
)
returns public.notification_preferences
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_preferences public.notification_preferences%rowtype;
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;

    insert into public.notification_preferences(
        family_id,
        feeding_enabled,
        medicine_enabled,
        vaccination_enabled,
        growth_enabled,
        briefing_enabled,
        health_alerts_enabled,
        daily_time,
        updated_by_id
    ) values (
        p_family_id,
        coalesce(p_feeding_enabled, true),
        coalesce(p_medicine_enabled, true),
        coalesce(p_vaccination_enabled, true),
        coalesce(p_growth_enabled, false),
        coalesce(p_briefing_enabled, true),
        coalesce(p_health_alerts_enabled, true),
        coalesce(p_daily_time, time '08:00'),
        v_current.id
    )
    on conflict (family_id) do update set
        feeding_enabled = excluded.feeding_enabled,
        medicine_enabled = excluded.medicine_enabled,
        vaccination_enabled = excluded.vaccination_enabled,
        growth_enabled = excluded.growth_enabled,
        briefing_enabled = excluded.briefing_enabled,
        health_alerts_enabled = excluded.health_alerts_enabled,
        daily_time = excluded.daily_time,
        updated_by_id = excluded.updated_by_id,
        updated_at = now()
    returning * into v_preferences;

    return v_preferences;
end;
$$;

create or replace function public.create_family_invitation_checked(
    p_family_id bigint,
    p_email text,
    p_relationship text,
    p_note text
)
returns public.family_invitations
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_invitation public.family_invitations%rowtype;
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if trim(coalesce(p_email, '')) = '' then raise exception 'Invitation email is required'; end if;
    if trim(coalesce(p_relationship, '')) = '' then raise exception 'Invitation relationship is required'; end if;

    insert into public.family_invitations(family_id, email, relationship, note, invited_by_id)
    values (p_family_id, lower(trim(p_email)), trim(p_relationship), nullif(trim(coalesce(p_note, '')), ''), v_current.id)
    returning * into v_invitation;

    return v_invitation;
end;
$$;

create or replace function public.request_data_export_checked(
    p_family_id bigint,
    p_format text,
    p_sections jsonb
)
returns public.export_jobs
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_job public.export_jobs%rowtype;
    v_format text := upper(trim(coalesce(p_format, 'PDF')));
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_format not in ('PDF','EXCEL','CSV') then raise exception 'Invalid export format'; end if;

    insert into public.export_jobs(family_id, requested_by_id, format, sections)
    values (p_family_id, v_current.id, v_format, coalesce(p_sections, '[]'::jsonb))
    returning * into v_job;

    return v_job;
end;
$$;

revoke all on function public.care_record_label(text) from public, anon;
revoke all on function public.create_care_record_with_chat(bigint, bigint, text, text, text, timestamptz, timestamptz, text, jsonb) from public, anon;
revoke all on function public.update_care_record_checked(bigint, text, text, timestamptz, timestamptz, text, jsonb) from public, anon;
revoke all on function public.delete_care_record_checked(bigint) from public, anon;
revoke all on function public.create_growth_measurement_checked(bigint, bigint, timestamptz, numeric, numeric, numeric, text) from public, anon;
revoke all on function public.upsert_notification_preferences_checked(bigint, boolean, boolean, boolean, boolean, boolean, boolean, time) from public, anon;
revoke all on function public.create_family_invitation_checked(bigint, text, text, text) from public, anon;
revoke all on function public.request_data_export_checked(bigint, text, jsonb) from public, anon;

grant execute on function public.care_record_label(text) to authenticated;
grant execute on function public.create_care_record_with_chat(bigint, bigint, text, text, text, timestamptz, timestamptz, text, jsonb) to authenticated;
grant execute on function public.update_care_record_checked(bigint, text, text, timestamptz, timestamptz, text, jsonb) to authenticated;
grant execute on function public.delete_care_record_checked(bigint) to authenticated;
grant execute on function public.create_growth_measurement_checked(bigint, bigint, timestamptz, numeric, numeric, numeric, text) to authenticated;
grant execute on function public.upsert_notification_preferences_checked(bigint, boolean, boolean, boolean, boolean, boolean, boolean, time) to authenticated;
grant execute on function public.create_family_invitation_checked(bigint, text, text, text) to authenticated;
grant execute on function public.request_data_export_checked(bigint, text, jsonb) to authenticated;

insert into public.notification_preferences(family_id, updated_by_id)
select f.id, null
from public.families f
on conflict (family_id) do nothing;
