-- Account and family deletion lifecycle.
-- Individual caregivers can leave a shared family while shared content remains.
-- A family owner can schedule a whole-family purge, with a 30 day cancellation window.

alter table public.families
    add column if not exists owner_caregiver_id bigint,
    add column if not exists deletion_requested_at timestamptz,
    add column if not exists deletion_scheduled_for timestamptz,
    add column if not exists deletion_requested_by_auth_user_id uuid;

update public.families family
set owner_caregiver_id = (
    select caregiver.id
    from public.caregivers caregiver
    where caregiver.family_id = family.id
    order by caregiver.id asc
    limit 1
)
where family.owner_caregiver_id is null;

alter table public.families
    drop constraint if exists families_owner_caregiver_id_fkey;

alter table public.families
    add constraint families_owner_caregiver_id_fkey
    foreign key (owner_caregiver_id)
    references public.caregivers(id)
    on delete set null;

alter table public.chat_messages
    alter column sender_id drop not null;

alter table public.chat_messages
    drop constraint if exists chat_messages_sender_id_fkey;

alter table public.chat_messages
    add constraint chat_messages_sender_id_fkey
    foreign key (sender_id)
    references public.caregivers(id)
    on delete set null;

alter table public.family_chat_messages
    alter column sender_caregiver_id drop not null;

alter table public.family_chat_messages
    drop constraint if exists family_chat_messages_sender_caregiver_id_fkey;

alter table public.family_chat_messages
    add constraint family_chat_messages_sender_caregiver_id_fkey
    foreign key (sender_caregiver_id)
    references public.caregivers(id)
    on delete set null;

alter table public.family_photos
    alter column created_by_id drop not null;

alter table public.family_photos
    drop constraint if exists family_photos_created_by_id_fkey;

alter table public.family_photos
    add constraint family_photos_created_by_id_fkey
    foreign key (created_by_id)
    references public.caregivers(id)
    on delete set null;

alter table public.timeline_comments
    alter column author_caregiver_id drop not null;

alter table public.timeline_comments
    drop constraint if exists timeline_comments_author_caregiver_id_fkey;

alter table public.timeline_comments
    add constraint timeline_comments_author_caregiver_id_fkey
    foreign key (author_caregiver_id)
    references public.caregivers(id)
    on delete set null;

create table if not exists public.account_deletion_audit (
    id bigint generated by default as identity primary key,
    family_id bigint,
    caregiver_id bigint,
    auth_user_id uuid,
    action text not null check (action in ('CAREGIVER_DELETED', 'FAMILY_DELETION_SCHEDULED', 'FAMILY_DELETION_CANCELLED', 'FAMILY_DELETED')),
    scheduled_for timestamptz,
    completed_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.account_deletion_audit enable row level security;
revoke all on public.account_deletion_audit from public, anon, authenticated;

create or replace function public.assert_recent_reauthentication()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_issued_at bigint;
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    v_issued_at := nullif(auth.jwt() ->> 'iat', '')::bigint;

    if v_issued_at is null or to_timestamp(v_issued_at) < now() - interval '10 minutes' then
        raise exception 'Recent reauthentication is required';
    end if;
end;
$$;

create or replace function public.request_caregiver_account_deletion_checked()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_current public.caregivers%rowtype;
    v_family public.families%rowtype;
    v_successor_caregiver_id bigint;
    v_successor_auth_user_id uuid;
    v_caregiver_count integer;
begin
    perform public.assert_recent_reauthentication();

    select *
    into v_current
    from public.caregivers caregiver
    where caregiver.auth_user_id = auth.uid()
    for update;

    if not found then
        raise exception 'Current caregiver was not found';
    end if;

    select *
    into v_family
    from public.families family
    where family.id = v_current.family_id
    for update;

    select count(*)
    into v_caregiver_count
    from public.caregivers caregiver
    where caregiver.family_id = v_current.family_id;

    if v_caregiver_count <= 1 then
        raise exception 'At least one other caregiver must remain';
    end if;

    select caregiver.id, caregiver.auth_user_id
    into v_successor_caregiver_id, v_successor_auth_user_id
    from public.caregivers caregiver
    where caregiver.family_id = v_current.family_id
      and caregiver.id <> v_current.id
      and caregiver.auth_user_id is not null
    order by caregiver.id asc
    limit 1;

    if v_successor_auth_user_id is null then
        raise exception 'A remaining caregiver with an active account is required';
    end if;

    update storage.objects object
    set owner = v_successor_auth_user_id,
        owner_id = v_successor_auth_user_id::text,
        updated_at = now()
    where object.bucket_id = 'family-media'
      and object.owner = auth.uid()
      and (
          object.name like 'photos/' || v_current.family_id::text || '/%'
          or object.name like 'chat/' || v_current.family_id::text || '/%'
      );

    if v_family.owner_caregiver_id = v_current.id then
        update public.families
        set owner_caregiver_id = v_successor_caregiver_id
        where id = v_current.family_id;
    end if;

    insert into public.account_deletion_audit(family_id, caregiver_id, auth_user_id, action, completed_at, metadata)
    values (
        v_current.family_id,
        v_current.id,
        auth.uid(),
        'CAREGIVER_DELETED',
        now(),
        jsonb_build_object('shared_content_retained', true)
    );

    delete from public.caregivers
    where id = v_current.id;

    delete from auth.users user_row
    where user_row.id = auth.uid()
      and not exists (
          select 1
          from public.caregivers caregiver
          where caregiver.auth_user_id = user_row.id
      );
end;
$$;

create or replace function public.schedule_family_deletion_checked()
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_current public.caregivers%rowtype;
    v_family public.families%rowtype;
    v_scheduled_for timestamptz := now() + interval '30 days';
begin
    perform public.assert_recent_reauthentication();

    select *
    into v_current
    from public.caregivers caregiver
    where caregiver.auth_user_id = auth.uid()
    for update;

    if not found then
        raise exception 'Current caregiver was not found';
    end if;

    select *
    into v_family
    from public.families family
    where family.id = v_current.family_id
    for update;

    if v_family.owner_caregiver_id is distinct from v_current.id then
        raise exception 'Only the family owner can schedule deletion';
    end if;

    if v_family.deletion_scheduled_for is not null then
        raise exception 'Family deletion is already scheduled';
    end if;

    update public.families
    set deletion_requested_at = now(),
        deletion_scheduled_for = v_scheduled_for,
        deletion_requested_by_auth_user_id = auth.uid()
    where id = v_family.id;

    insert into public.account_deletion_audit(family_id, caregiver_id, auth_user_id, action, scheduled_for)
    values (v_family.id, v_current.id, auth.uid(), 'FAMILY_DELETION_SCHEDULED', v_scheduled_for);

    return v_scheduled_for;
end;
$$;

create or replace function public.cancel_family_deletion_checked()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_current public.caregivers%rowtype;
    v_family public.families%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    select *
    into v_current
    from public.caregivers caregiver
    where caregiver.auth_user_id = auth.uid()
    for update;

    if not found then
        raise exception 'Current caregiver was not found';
    end if;

    select *
    into v_family
    from public.families family
    where family.id = v_current.family_id
    for update;

    if v_family.owner_caregiver_id is distinct from v_current.id then
        raise exception 'Only the family owner can cancel deletion';
    end if;

    if v_family.deletion_scheduled_for is null then
        raise exception 'No family deletion is scheduled';
    end if;

    update public.families
    set deletion_requested_at = null,
        deletion_scheduled_for = null,
        deletion_requested_by_auth_user_id = null
    where id = v_family.id;

    insert into public.account_deletion_audit(family_id, caregiver_id, auth_user_id, action)
    values (v_family.id, v_current.id, auth.uid(), 'FAMILY_DELETION_CANCELLED');
end;
$$;

create or replace function public.purge_due_family_deletions(p_limit integer default 50)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_family public.families%rowtype;
    v_auth_user_ids uuid[];
    v_deleted_count integer := 0;
    v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 200);
begin
    for v_family in
        select family.*
        from public.families family
        where family.deletion_scheduled_for is not null
          and family.deletion_scheduled_for <= now()
        order by family.deletion_scheduled_for asc
        limit v_limit
        for update skip locked
    loop
        select array_agg(caregiver.auth_user_id)
        into v_auth_user_ids
        from public.caregivers caregiver
        where caregiver.family_id = v_family.id
          and caregiver.auth_user_id is not null;

        delete from storage.objects object
        where object.bucket_id = 'family-media'
          and (
              object.name like 'photos/' || v_family.id::text || '/%'
              or object.name like 'chat/' || v_family.id::text || '/%'
          );

        insert into public.account_deletion_audit(family_id, auth_user_id, action, scheduled_for, completed_at, metadata)
        values (
            v_family.id,
            v_family.deletion_requested_by_auth_user_id,
            'FAMILY_DELETED',
            v_family.deletion_scheduled_for,
            now(),
            jsonb_build_object('family_name', v_family.name)
        );

        delete from public.families
        where id = v_family.id;

        if coalesce(array_length(v_auth_user_ids, 1), 0) > 0 then
            delete from auth.users user_row
            where user_row.id = any(v_auth_user_ids)
              and not exists (
                  select 1
                  from public.caregivers caregiver
                  where caregiver.auth_user_id = user_row.id
              );
        end if;

        v_deleted_count := v_deleted_count + 1;
    end loop;

    return v_deleted_count;
end;
$$;

revoke all on function public.assert_recent_reauthentication() from public, anon, authenticated;
revoke all on function public.request_caregiver_account_deletion_checked() from public, anon;
revoke all on function public.schedule_family_deletion_checked() from public, anon;
revoke all on function public.cancel_family_deletion_checked() from public, anon;
revoke all on function public.purge_due_family_deletions(integer) from public, anon, authenticated;

grant execute on function public.request_caregiver_account_deletion_checked() to authenticated;
grant execute on function public.schedule_family_deletion_checked() to authenticated;
grant execute on function public.cancel_family_deletion_checked() to authenticated;
grant execute on function public.purge_due_family_deletions(integer) to service_role;

create extension if not exists pg_cron;

select cron.schedule(
    'ilog-purge-family-deletions',
    '17 * * * *',
    $cron$
    select public.purge_due_family_deletions(50);
    $cron$
);
