-- 아이로그 Supabase current-state baseline.
-- Use this for a fresh Supabase project. Do not re-apply to the existing
-- sflxzfxoyicpiykvgcte project, which already has remote migration history.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.families (
    id bigint generated by default as identity primary key,
    name text not null,
    invite_code text not null unique,
    subscription_plan text not null default 'FREE' check (subscription_plan in ('FREE', 'PREMIUM')),
    push_notifications_enabled boolean not null default true,
    chat_notifications_enabled boolean not null default true,
    morning_briefing_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.caregivers (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    auth_user_id uuid references auth.users(id) on delete set null,
    name text not null,
    role text not null check (role in ('MOM', 'DAD', 'GUARDIAN')),
    availability_score integer not null default 7 check (availability_score between 1 and 10),
    fatigue_score integer not null default 4 check (fatigue_score between 1 and 10),
    image_url text,
    pin_hash text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.children (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    name text not null,
    birth_date date not null,
    stage text not null check (stage in ('NEWBORN', 'INFANT', 'TODDLER', 'PRESCHOOL', 'EARLY_SCHOOL')),
    image_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint references public.children(id) on delete set null,
    assignee_id bigint references public.caregivers(id) on delete set null,
    created_by_id bigint references public.caregivers(id) on delete set null,
    title text not null,
    description text,
    due_at timestamptz not null,
    priority text not null default 'MEDIUM' check (priority in ('HIGH', 'MEDIUM', 'LOW')),
    status text not null default 'PENDING' check (status in ('PENDING', 'IN_PROGRESS', 'DONE')),
    auto_assigned boolean not null default false,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    reminder_minutes_before integer check (reminder_minutes_before is null or reminder_minutes_before >= 0),
    updated_at timestamptz not null default now()
);

create table if not exists public.schedules (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint references public.children(id) on delete set null,
    title text not null,
    category text not null check (category in ('HOSPITAL', 'VACCINE', 'DAYCARE', 'SCHOOL', 'HOME', 'ACTIVITY')),
    start_at timestamptz not null,
    end_at timestamptz not null,
    note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.logs (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint references public.children(id) on delete set null,
    caregiver_id bigint references public.caregivers(id) on delete set null,
    type text not null check (type in ('FEEDING', 'SLEEP', 'GROWTH', 'MOMENT', 'MEDICINE', 'CHECKLIST')),
    entry_value text not null,
    note text,
    recorded_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.memory_entries (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    child_id bigint references public.children(id) on delete set null,
    created_by_id bigint references public.caregivers(id) on delete set null,
    title text not null,
    note text,
    image_url text,
    tag text,
    happened_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    sender_id bigint not null references public.caregivers(id) on delete cascade,
    message_type text not null default 'TEXT' check (message_type in ('TEXT', 'TASK_LINK', 'LOG_UPDATE')),
    body text not null,
    linked_task_id bigint references public.tasks(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists caregivers_family_name_ci_key on public.caregivers(family_id, lower(name));
create unique index if not exists caregivers_auth_user_id_key on public.caregivers(auth_user_id) where auth_user_id is not null;
create index if not exists idx_caregivers_family_name on public.caregivers(family_id, name);
create index if not exists idx_tasks_family_due on public.tasks(family_id, due_at);
create index if not exists idx_tasks_family_created on public.tasks(family_id, created_at);
create index if not exists idx_tasks_assignee_due on public.tasks(assignee_id, due_at);
create index if not exists idx_tasks_assignee_completed on public.tasks(assignee_id, completed_at);
create index if not exists idx_schedules_family_start on public.schedules(family_id, start_at);
create index if not exists idx_logs_family_recorded on public.logs(family_id, recorded_at);
create index if not exists idx_memory_entries_family_happened on public.memory_entries(family_id, happened_at);
create index if not exists idx_chat_messages_family_created on public.chat_messages(family_id, created_at);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists families_touch_updated_at on public.families;
create trigger families_touch_updated_at before update on public.families for each row execute function public.touch_updated_at();
drop trigger if exists caregivers_touch_updated_at on public.caregivers;
create trigger caregivers_touch_updated_at before update on public.caregivers for each row execute function public.touch_updated_at();
drop trigger if exists children_touch_updated_at on public.children;
create trigger children_touch_updated_at before update on public.children for each row execute function public.touch_updated_at();
drop trigger if exists tasks_touch_updated_at on public.tasks;
create trigger tasks_touch_updated_at before update on public.tasks for each row execute function public.touch_updated_at();
drop trigger if exists schedules_touch_updated_at on public.schedules;
create trigger schedules_touch_updated_at before update on public.schedules for each row execute function public.touch_updated_at();
drop trigger if exists logs_touch_updated_at on public.logs;
create trigger logs_touch_updated_at before update on public.logs for each row execute function public.touch_updated_at();
drop trigger if exists memory_entries_touch_updated_at on public.memory_entries;
create trigger memory_entries_touch_updated_at before update on public.memory_entries for each row execute function public.touch_updated_at();
drop trigger if exists chat_messages_touch_updated_at on public.chat_messages;
create trigger chat_messages_touch_updated_at before update on public.chat_messages for each row execute function public.touch_updated_at();

create or replace function public.current_family_ids()
returns table(family_id bigint)
language sql
stable
security definer
set search_path = public
as $$
    select c.family_id
    from public.caregivers c
    where c.auth_user_id = auth.uid()
$$;

create or replace function public.current_caregiver_ids()
returns table(caregiver_id bigint)
language sql
stable
security definer
set search_path = public
as $$
    select c.id
    from public.caregivers c
    where c.auth_user_id = auth.uid()
$$;

create or replace function public.current_caregiver_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
    select c.id
    from public.caregivers as c
    where c.auth_user_id = auth.uid()
    order by c.updated_at desc
    limit 1
$$;

create or replace function public.is_family_member(target_family_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.caregivers c
        where c.family_id = target_family_id
          and c.auth_user_id = auth.uid()
    )
$$;

alter table public.families enable row level security;
alter table public.caregivers enable row level security;
alter table public.children enable row level security;
alter table public.tasks enable row level security;
alter table public.schedules enable row level security;
alter table public.logs enable row level security;
alter table public.memory_entries enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists families_select_member on public.families;
create policy families_select_member on public.families for select to authenticated using (public.is_family_member(id));
drop policy if exists families_update_member on public.families;
create policy families_update_member on public.families for update to authenticated using (public.is_family_member(id)) with check (public.is_family_member(id));

drop policy if exists caregivers_select_member on public.caregivers;
create policy caregivers_select_member on public.caregivers for select to authenticated using (public.is_family_member(family_id));
drop policy if exists caregivers_update_self on public.caregivers;
create policy caregivers_update_self on public.caregivers for update to authenticated using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());

drop policy if exists children_select_member on public.children;
create policy children_select_member on public.children for select to authenticated using (public.is_family_member(family_id));

drop policy if exists tasks_select_member on public.tasks;
create policy tasks_select_member on public.tasks for select to authenticated using (public.is_family_member(family_id));
drop policy if exists tasks_insert_member on public.tasks;
create policy tasks_insert_member on public.tasks for insert to authenticated with check (public.is_family_member(family_id));
drop policy if exists tasks_update_member on public.tasks;
create policy tasks_update_member on public.tasks for update to authenticated using (public.is_family_member(family_id)) with check (public.is_family_member(family_id));

drop policy if exists schedules_select_member on public.schedules;
create policy schedules_select_member on public.schedules for select to authenticated using (public.is_family_member(family_id));
drop policy if exists schedules_insert_member on public.schedules;
create policy schedules_insert_member on public.schedules for insert to authenticated with check (public.is_family_member(family_id));

drop policy if exists logs_select_member on public.logs;
create policy logs_select_member on public.logs for select to authenticated using (public.is_family_member(family_id));
drop policy if exists logs_insert_member on public.logs;
create policy logs_insert_member on public.logs for insert to authenticated with check (
    public.is_family_member(family_id)
    and (caregiver_id is null or caregiver_id = public.current_caregiver_id())
);

drop policy if exists memory_entries_select_member on public.memory_entries;
create policy memory_entries_select_member on public.memory_entries for select to authenticated using (public.is_family_member(family_id));
drop policy if exists memory_entries_insert_member on public.memory_entries;
create policy memory_entries_insert_member on public.memory_entries for insert to authenticated with check (
    public.is_family_member(family_id)
    and (created_by_id is null or created_by_id = public.current_caregiver_id())
);

drop policy if exists chat_messages_select_member on public.chat_messages;
create policy chat_messages_select_member on public.chat_messages for select to authenticated using (public.is_family_member(family_id));
drop policy if exists chat_messages_insert_member on public.chat_messages;
create policy chat_messages_insert_member on public.chat_messages for insert to authenticated with check (
    public.is_family_member(family_id)
    and sender_id = public.current_caregiver_id()
);

create or replace function public.join_family_by_invite(
    p_invite_code text,
    p_caregiver_name text,
    p_role text default null,
    p_availability_score integer default null,
    p_fatigue_score integer default null,
    p_pin_code text default ''
)
returns table(caregiver_id bigint, family_id bigint, child_id bigint)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_family public.families%rowtype;
    v_child public.children%rowtype;
    v_caregiver public.caregivers%rowtype;
    v_name text := trim(p_caregiver_name);
    v_pin text := trim(coalesce(p_pin_code, ''));
    v_next_role text;
    v_next_availability integer;
    v_next_fatigue integer;
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    if v_name = '' then
        raise exception 'Caregiver name is required';
    end if;

    if v_pin !~ '^\d{4}$' then
        raise exception 'PIN must be 4 digits';
    end if;

    if p_role is not null and p_role not in ('MOM', 'DAD', 'GUARDIAN') then
        raise exception 'Invalid caregiver role';
    end if;

    select * into v_family
    from public.families
    where upper(invite_code) = upper(trim(p_invite_code))
    limit 1;

    if not found then
        raise exception 'Family invite code was not found';
    end if;

    select * into v_child
    from public.children
    where family_id = v_family.id
    order by id asc
    limit 1;

    select * into v_caregiver
    from public.caregivers
    where family_id = v_family.id
      and lower(name) = lower(v_name)
    limit 1;

    if found then
        if coalesce(v_caregiver.pin_hash, '') <> ''
           and v_caregiver.pin_hash <> extensions.crypt(v_pin, v_caregiver.pin_hash) then
            raise exception 'Invalid caregiver PIN';
        end if;

        v_next_role := coalesce(p_role, v_caregiver.role, 'GUARDIAN');
        v_next_availability := coalesce(p_availability_score, v_caregiver.availability_score, 7);
        v_next_fatigue := coalesce(p_fatigue_score, v_caregiver.fatigue_score, 4);

        update public.caregivers
        set auth_user_id = null,
            updated_at = now()
        where auth_user_id = auth.uid()
          and id <> v_caregiver.id;

        update public.caregivers
        set auth_user_id = auth.uid(),
            role = v_next_role,
            availability_score = v_next_availability,
            fatigue_score = v_next_fatigue,
            pin_hash = case
                when coalesce(pin_hash, '') = '' then extensions.crypt(v_pin, extensions.gen_salt('bf'))
                else pin_hash
            end,
            updated_at = now()
        where id = v_caregiver.id
        returning * into v_caregiver;
    else
        v_next_role := coalesce(p_role, 'GUARDIAN');
        v_next_availability := coalesce(p_availability_score, 7);
        v_next_fatigue := coalesce(p_fatigue_score, 4);

        update public.caregivers
        set auth_user_id = null,
            updated_at = now()
        where auth_user_id = auth.uid();

        insert into public.caregivers(family_id, auth_user_id, name, role, availability_score, fatigue_score, pin_hash)
        values (v_family.id, auth.uid(), v_name, v_next_role, v_next_availability, v_next_fatigue, extensions.crypt(v_pin, extensions.gen_salt('bf')))
        returning * into v_caregiver;
    end if;

    return query select v_caregiver.id, v_family.id, v_child.id;
end;
$$;

create or replace function public.current_caregiver()
returns public.caregivers
language plpgsql
stable
set search_path = public
as $$
declare
    v_caregiver public.caregivers%rowtype;
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    select * into v_caregiver
    from public.caregivers
    where auth_user_id = auth.uid()
    order by updated_at desc
    limit 1;

    if not found then
        raise exception 'Current caregiver was not found';
    end if;

    return v_caregiver;
end;
$$;

create or replace function public.resolve_family_child(p_family_id bigint, p_child_id bigint default null)
returns public.children
language plpgsql
stable
set search_path = public
as $$
declare
    v_child public.children%rowtype;
begin
    if p_child_id is not null then
        select * into v_child from public.children where id = p_child_id and family_id = p_family_id limit 1;
    else
        select * into v_child from public.children where family_id = p_family_id order by id asc limit 1;
    end if;

    if not found then
        raise exception 'Child profile was not found';
    end if;

    return v_child;
end;
$$;

create or replace function public.select_task_assignee(p_family_id bigint)
returns public.caregivers
language plpgsql
stable
set search_path = public
as $$
declare
    v_caregiver public.caregivers%rowtype;
begin
    select c.* into v_caregiver
    from public.caregivers c
    left join lateral (
        select count(*)::numeric as recent_completed_tasks
        from public.tasks t
        where t.assignee_id = c.id
          and t.family_id = p_family_id
          and t.status = 'DONE'
          and t.completed_at >= now() - interval '7 days'
    ) rc on true
    left join lateral (
        select count(*)::numeric as pending_tasks_today
        from public.tasks t
        where t.assignee_id = c.id
          and t.family_id = p_family_id
          and t.status <> 'DONE'
          and t.due_at between date_trunc('day', now()) and date_trunc('day', now()) + interval '1 day' - interval '1 millisecond'
    ) pt on true
    where c.family_id = p_family_id
    order by round((coalesce(rc.recent_completed_tasks, 0) * 0.45 + coalesce(pt.pending_tasks_today, 0) * 0.80 + ((10 - c.availability_score) * 0.35) + (c.fatigue_score * 0.45))::numeric, 2), coalesce(pt.pending_tasks_today, 0), c.id
    limit 1;

    if not found then
        raise exception 'Assignable caregiver was not found';
    end if;

    return v_caregiver;
end;
$$;

create or replace function public.create_task_with_chat(
    p_family_id bigint,
    p_child_id bigint,
    p_assignee_id bigint,
    p_title text,
    p_description text,
    p_due_at timestamptz,
    p_priority text default 'MEDIUM',
    p_reminder_minutes_before integer default null
)
returns public.tasks
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_assignee public.caregivers%rowtype;
    v_task public.tasks%rowtype;
    v_title text := trim(coalesce(p_title, ''));
    v_priority text := coalesce(p_priority, 'MEDIUM');
    v_reminder_message text := '';
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_title = '' then raise exception 'Task title is required'; end if;
    if p_due_at is null then raise exception 'Task due time is required'; end if;
    if v_priority not in ('HIGH', 'MEDIUM', 'LOW') then raise exception 'Invalid task priority'; end if;
    if p_reminder_minutes_before is not null and (p_reminder_minutes_before < 5 or p_reminder_minutes_before > 1440) then raise exception 'Reminder minutes must be between 5 and 1440'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);

    if p_assignee_id is not null then
        select * into v_assignee from public.caregivers where id = p_assignee_id and family_id = p_family_id limit 1;
        if not found then raise exception 'Assignee caregiver was not found'; end if;
    else
        v_assignee := public.select_task_assignee(p_family_id);
    end if;

    insert into public.tasks(family_id, child_id, assignee_id, created_by_id, title, description, due_at, priority, status, auto_assigned, reminder_minutes_before)
    values (p_family_id, v_child.id, v_assignee.id, v_current.id, v_title, nullif(trim(coalesce(p_description, '')), ''), p_due_at, v_priority, 'PENDING', p_assignee_id is null, p_reminder_minutes_before)
    returning * into v_task;

    if v_task.reminder_minutes_before is not null then
        v_reminder_message := format(' 리마인더는 %s분 전에 알려드릴게요.', v_task.reminder_minutes_before);
    end if;

    insert into public.chat_messages(family_id, sender_id, body, message_type, linked_task_id)
    values (p_family_id, v_current.id, format('%s님 담당으로 %s 일을 등록했어요.%s', v_assignee.name, v_task.title, v_reminder_message), 'TASK_LINK', v_task.id);

    return v_task;
end;
$$;

create or replace function public.complete_task_with_chat(p_task_id bigint)
returns public.tasks
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_task public.tasks%rowtype;
begin
    v_current := public.current_caregiver();
    select * into v_task from public.tasks where id = p_task_id and family_id = v_current.family_id limit 1;
    if not found then raise exception 'Task was not found'; end if;
    if v_task.status = 'DONE' then return v_task; end if;

    update public.tasks set status = 'DONE', completed_at = now(), updated_at = now()
    where id = p_task_id and family_id = v_current.family_id
    returning * into v_task;

    insert into public.chat_messages(family_id, sender_id, body, message_type, linked_task_id)
    values (v_current.family_id, v_current.id, format('%s 일을 완료했어요.', v_task.title), 'TASK_LINK', v_task.id);

    return v_task;
end;
$$;

create or replace function public.create_log_with_chat(
    p_family_id bigint,
    p_child_id bigint,
    p_type text,
    p_value text,
    p_note text,
    p_recorded_at timestamptz
)
returns public.logs
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_log public.logs%rowtype;
    v_value text := trim(coalesce(p_value, ''));
    v_label text;
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if p_type not in ('FEEDING', 'SLEEP', 'GROWTH', 'MOMENT', 'MEDICINE', 'CHECKLIST') then raise exception 'Invalid log type'; end if;
    if v_value = '' then raise exception 'Log value is required'; end if;
    if p_recorded_at is null then raise exception 'Recorded time is required'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);
    insert into public.logs(family_id, child_id, caregiver_id, type, entry_value, note, recorded_at)
    values (p_family_id, v_child.id, v_current.id, p_type, v_value, nullif(trim(coalesce(p_note, '')), ''), p_recorded_at)
    returning * into v_log;

    v_label := case v_log.type when 'FEEDING' then '수유' when 'SLEEP' then '수면' when 'GROWTH' then '성장' when 'MOMENT' then '순간' when 'MEDICINE' then '복약' when 'CHECKLIST' then '체크리스트' else '생활' end;

    insert into public.chat_messages(family_id, sender_id, body, message_type)
    values (p_family_id, v_current.id, format('%s 기록을 남겼어요: %s', v_label, v_log.entry_value), 'LOG_UPDATE');

    return v_log;
end;
$$;

create or replace function public.create_schedule_with_chat(
    p_family_id bigint,
    p_child_id bigint,
    p_title text,
    p_category text,
    p_start_at timestamptz,
    p_end_at timestamptz,
    p_note text
)
returns public.schedules
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_schedule public.schedules%rowtype;
    v_title text := trim(coalesce(p_title, ''));
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_title = '' then raise exception 'Schedule title is required'; end if;
    if p_category not in ('HOSPITAL', 'VACCINE', 'DAYCARE', 'SCHOOL', 'HOME', 'ACTIVITY') then raise exception 'Invalid schedule category'; end if;
    if p_start_at is null or p_end_at is null then raise exception 'Schedule times are required'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);
    insert into public.schedules(family_id, child_id, title, category, start_at, end_at, note)
    values (p_family_id, v_child.id, v_title, p_category, p_start_at, p_end_at, nullif(trim(coalesce(p_note, '')), ''))
    returning * into v_schedule;

    insert into public.chat_messages(family_id, sender_id, body, message_type)
    values (p_family_id, v_current.id, format('%s 일정을 등록했어요.', v_schedule.title), 'TEXT');

    return v_schedule;
end;
$$;

create or replace function public.create_memory_with_chat(
    p_family_id bigint,
    p_child_id bigint,
    p_title text,
    p_note text,
    p_image_url text,
    p_tag text,
    p_happened_at timestamptz
)
returns public.memory_entries
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_child public.children%rowtype;
    v_memory public.memory_entries%rowtype;
    v_title text := trim(coalesce(p_title, ''));
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_title = '' then raise exception 'Memory title is required'; end if;
    if p_happened_at is null then raise exception 'Memory time is required'; end if;

    v_child := public.resolve_family_child(p_family_id, p_child_id);
    insert into public.memory_entries(family_id, child_id, created_by_id, title, note, image_url, tag, happened_at)
    values (p_family_id, v_child.id, v_current.id, v_title, nullif(trim(coalesce(p_note, '')), ''), nullif(trim(coalesce(p_image_url, '')), ''), nullif(trim(coalesce(p_tag, '')), ''), p_happened_at)
    returning * into v_memory;

    insert into public.chat_messages(family_id, sender_id, body, message_type)
    values (p_family_id, v_current.id, format('수첩 기록을 남겼어요: %s', v_memory.title), 'LOG_UPDATE');

    return v_memory;
end;
$$;

create or replace function public.create_chat_message_checked(
    p_family_id bigint,
    p_body text,
    p_message_type text default 'TEXT',
    p_linked_task_id bigint default null
)
returns public.chat_messages
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_task public.tasks%rowtype;
    v_message public.chat_messages%rowtype;
    v_body text := trim(coalesce(p_body, ''));
    v_message_type text := coalesce(p_message_type, 'TEXT');
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_body = '' then raise exception 'Message body is required'; end if;
    if v_message_type not in ('TEXT', 'TASK_LINK', 'LOG_UPDATE') then raise exception 'Invalid chat message type'; end if;

    if p_linked_task_id is not null then
        select * into v_task from public.tasks where id = p_linked_task_id and family_id = p_family_id limit 1;
        if not found then raise exception 'Linked task was not found'; end if;
    end if;

    insert into public.chat_messages(family_id, sender_id, body, message_type, linked_task_id)
    values (p_family_id, v_current.id, v_body, v_message_type, p_linked_task_id)
    returning * into v_message;

    return v_message;
end;
$$;

revoke all on all tables in schema public from anon;
revoke all on all tables in schema public from authenticated;
revoke all on all sequences in schema public from anon;
revoke all on all sequences in schema public from authenticated;
revoke execute on all functions in schema public from public;
revoke execute on all functions in schema public from anon;
revoke execute on all functions in schema public from authenticated;

grant select on public.families, public.children, public.caregivers, public.tasks, public.schedules, public.logs, public.memory_entries, public.chat_messages to authenticated;
grant insert on public.tasks, public.schedules, public.logs, public.memory_entries, public.chat_messages to authenticated;
grant update on public.families, public.tasks to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.current_family_ids() to authenticated;
grant execute on function public.current_caregiver_ids() to authenticated;
grant execute on function public.current_caregiver_id() to authenticated;
grant execute on function public.is_family_member(bigint) to authenticated;
grant execute on function public.join_family_by_invite(text, text, text, integer, integer, text) to authenticated;
grant execute on function public.current_caregiver() to authenticated;
grant execute on function public.resolve_family_child(bigint, bigint) to authenticated;
grant execute on function public.select_task_assignee(bigint) to authenticated;
grant execute on function public.create_task_with_chat(bigint, bigint, bigint, text, text, timestamptz, text, integer) to authenticated;
grant execute on function public.complete_task_with_chat(bigint) to authenticated;
grant execute on function public.create_log_with_chat(bigint, bigint, text, text, text, timestamptz) to authenticated;
grant execute on function public.create_schedule_with_chat(bigint, bigint, text, text, timestamptz, timestamptz, text) to authenticated;
grant execute on function public.create_memory_with_chat(bigint, bigint, text, text, text, text, timestamptz) to authenticated;
grant execute on function public.create_chat_message_checked(bigint, text, text, bigint) to authenticated;

insert into public.families(id, name, invite_code, subscription_plan, push_notifications_enabled, chat_notifications_enabled, morning_briefing_enabled)
values (1, '다이 가족 공동육아 보드', 'BB-FAMILY', 'FREE', true, true, true)
on conflict (id) do nothing;

insert into public.children(id, family_id, name, birth_date, stage)
values (1, 1, '다이', date '2024-09-02', 'TODDLER')
on conflict (id) do nothing;

insert into public.caregivers(id, family_id, name, role, availability_score, fatigue_score, pin_hash)
values
    (1, 1, '지윤', 'MOM', 7, 4, extensions.crypt('1111', extensions.gen_salt('bf'))),
    (2, 1, '민수', 'DAD', 6, 5, extensions.crypt('2222', extensions.gen_salt('bf')))
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.families', 'id'), coalesce((select max(id) from public.families), 1), true);
select setval(pg_get_serial_sequence('public.children', 'id'), coalesce((select max(id) from public.children), 1), true);
select setval(pg_get_serial_sequence('public.caregivers', 'id'), coalesce((select max(id) from public.caregivers), 1), true);
