-- Private family media and a separate family-chat stream.
-- Timeline messages stay untouched so record history remains distinct from chat.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'family-media',
    'family-media',
    false,
    6291456,
    array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']::text[]
)
on conflict (id) do update set
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.family_photos (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    created_by_id bigint not null references public.caregivers(id) on delete cascade,
    storage_path text not null unique,
    caption text,
    created_at timestamptz not null default now(),
    constraint family_photos_storage_path_check check (storage_path ~ '^photos/[0-9]+/[A-Za-z0-9._-]+$')
);

create table if not exists public.family_chat_messages (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    sender_caregiver_id bigint not null references public.caregivers(id) on delete cascade,
    body text not null default '',
    image_storage_path text,
    created_at timestamptz not null default now(),
    constraint family_chat_messages_content_check check (
        nullif(btrim(body), '') is not null or image_storage_path is not null
    ),
    constraint family_chat_messages_image_path_check check (
        image_storage_path is null or image_storage_path ~ '^chat/[0-9]+/[A-Za-z0-9._-]+$'
    )
);

create index if not exists idx_family_photos_family_created
    on public.family_photos(family_id, created_at desc);
create index if not exists idx_family_chat_messages_family_created
    on public.family_chat_messages(family_id, created_at desc);

alter table public.family_photos enable row level security;
alter table public.family_chat_messages enable row level security;

drop policy if exists family_photos_select_member on public.family_photos;
create policy family_photos_select_member on public.family_photos
    for select to authenticated
    using (public.is_family_member(family_id));

drop policy if exists family_photos_insert_member on public.family_photos;
create policy family_photos_insert_member on public.family_photos
    for insert to authenticated
    with check (
        public.is_family_member(family_id)
        and created_by_id = public.current_caregiver_id()
    );

drop policy if exists family_chat_messages_select_member on public.family_chat_messages;
create policy family_chat_messages_select_member on public.family_chat_messages
    for select to authenticated
    using (public.is_family_member(family_id));

drop policy if exists family_chat_messages_insert_member on public.family_chat_messages;
create policy family_chat_messages_insert_member on public.family_chat_messages
    for insert to authenticated
    with check (
        public.is_family_member(family_id)
        and sender_caregiver_id = public.current_caregiver_id()
    );

drop policy if exists family_media_select_member on storage.objects;
create policy family_media_select_member on storage.objects
    for select to authenticated
    using (
        bucket_id = 'family-media'
        and (storage.foldername(name))[1] in ('photos', 'chat')
        and (storage.foldername(name))[2] = ((public.current_caregiver()).family_id)::text
    );

drop policy if exists family_media_insert_member on storage.objects;
create policy family_media_insert_member on storage.objects
    for insert to authenticated
    with check (
        bucket_id = 'family-media'
        and (storage.foldername(name))[1] in ('photos', 'chat')
        and (storage.foldername(name))[2] = ((public.current_caregiver()).family_id)::text
    );

create or replace function public.create_family_photo_checked(
    p_family_id bigint,
    p_storage_path text,
    p_caption text default null
)
returns public.family_photos
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_photo public.family_photos%rowtype;
    v_storage_path text := trim(coalesce(p_storage_path, ''));
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_storage_path !~ ('^photos/' || p_family_id::text || '/[A-Za-z0-9._-]+$') then
        raise exception 'Invalid family photo path';
    end if;

    insert into public.family_photos(family_id, created_by_id, storage_path, caption)
    values (p_family_id, v_current.id, v_storage_path, nullif(trim(coalesce(p_caption, '')), ''))
    returning * into v_photo;

    return v_photo;
end;
$$;

create or replace function public.create_family_chat_message_checked(
    p_family_id bigint,
    p_body text default '',
    p_image_storage_path text default null
)
returns public.family_chat_messages
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_message public.family_chat_messages%rowtype;
    v_recipient record;
    v_body text := trim(coalesce(p_body, ''));
    v_image_storage_path text := nullif(trim(coalesce(p_image_storage_path, '')), '');
    v_preview text;
    v_mentioned boolean;
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_body = '' and v_image_storage_path is null then raise exception 'Message content is required'; end if;
    if v_image_storage_path is not null
       and v_image_storage_path !~ ('^chat/' || p_family_id::text || '/[A-Za-z0-9._-]+$') then
        raise exception 'Invalid family chat image path';
    end if;

    insert into public.family_chat_messages(family_id, sender_caregiver_id, body, image_storage_path)
    values (p_family_id, v_current.id, v_body, v_image_storage_path)
    returning * into v_message;

    v_preview := coalesce(nullif(v_body, ''), '사진을 보냈어요.');

    for v_recipient in
        select c.id, c.name
        from public.caregivers c
        join public.families f on f.id = c.family_id
        where c.family_id = p_family_id
          and c.id <> v_current.id
          and f.push_notifications_enabled
          and f.chat_notifications_enabled
    loop
        v_mentioned := position(lower('@' || v_recipient.name) in lower(v_body)) > 0;

        insert into public.push_notification_events(
            family_id,
            recipient_caregiver_id,
            actor_caregiver_id,
            event_type,
            title,
            body,
            data
        ) values (
            p_family_id,
            v_recipient.id,
            v_current.id,
            case when v_mentioned then 'FAMILY_CHAT_MENTION' else 'FAMILY_CHAT' end,
            case when v_mentioned then '가족 대화에서 나를 언급했어요' else '새 가족 메시지' end,
            left(format('%s: %s', v_current.name, v_preview), 180),
            jsonb_build_object(
                'familyChatMessageId', v_message.id,
                'route', '/family-chat'
            )
        );
    end loop;

    return v_message;
end;
$$;

alter table public.push_notification_events
    drop constraint if exists push_notification_events_event_type_check;

alter table public.push_notification_events
    add constraint push_notification_events_event_type_check check (
        event_type in (
            'TIMELINE_COMMENT',
            'TIMELINE_REPLY',
            'FAMILY_CHAT',
            'FAMILY_CHAT_MENTION',
            'RECORD_ALARM',
            'TASK_REMINDER',
            'RECORD_SHARED'
        )
    );

revoke all on public.family_photos, public.family_chat_messages from anon, public;
grant select, insert on public.family_photos, public.family_chat_messages to authenticated;
grant usage, select on sequence public.family_photos_id_seq, public.family_chat_messages_id_seq to authenticated;

revoke all on function public.create_family_photo_checked(bigint, text, text) from public, anon;
revoke all on function public.create_family_chat_message_checked(bigint, text, text) from public, anon;
grant execute on function public.create_family_photo_checked(bigint, text, text) to authenticated;
grant execute on function public.create_family_chat_message_checked(bigint, text, text) to authenticated;
