create table if not exists public.timeline_comments (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    chat_message_id bigint not null references public.chat_messages(id) on delete cascade,
    parent_comment_id bigint references public.timeline_comments(id) on delete cascade,
    author_caregiver_id bigint not null references public.caregivers(id) on delete cascade,
    body text not null check (char_length(trim(body)) between 1 and 1000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (parent_comment_id is null or parent_comment_id <> id)
);

create table if not exists public.push_device_tokens (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    caregiver_id bigint not null references public.caregivers(id) on delete cascade,
    expo_push_token text not null check (char_length(trim(expo_push_token)) > 0),
    platform text not null default 'unknown' check (platform in ('ios','android','web','unknown')),
    device_id text,
    app_version text,
    enabled boolean not null default true,
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (caregiver_id, expo_push_token)
);

create table if not exists public.push_notification_events (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    recipient_caregiver_id bigint not null references public.caregivers(id) on delete cascade,
    actor_caregiver_id bigint references public.caregivers(id) on delete set null,
    event_type text not null check (event_type in ('TIMELINE_COMMENT','TIMELINE_REPLY')),
    title text not null,
    body text not null,
    data jsonb not null default '{}'::jsonb,
    status text not null default 'PENDING' check (status in ('PENDING','SENT','FAILED','SKIPPED')),
    attempts integer not null default 0 check (attempts >= 0),
    error_message text,
    created_at timestamptz not null default now(),
    sent_at timestamptz,
    updated_at timestamptz not null default now()
);

create index if not exists idx_timeline_comments_message_created on public.timeline_comments(chat_message_id, created_at);
create index if not exists idx_timeline_comments_family_created on public.timeline_comments(family_id, created_at desc);
create index if not exists idx_timeline_comments_parent on public.timeline_comments(parent_comment_id);
create index if not exists idx_push_device_tokens_caregiver on public.push_device_tokens(caregiver_id, enabled);
create index if not exists idx_push_notification_events_pending on public.push_notification_events(status, created_at)
    where status = 'PENDING';
create index if not exists idx_push_notification_events_family_recipient on public.push_notification_events(family_id, recipient_caregiver_id, created_at desc);

drop trigger if exists timeline_comments_touch_updated_at on public.timeline_comments;
create trigger timeline_comments_touch_updated_at before update on public.timeline_comments for each row execute function public.touch_updated_at();

drop trigger if exists push_device_tokens_touch_updated_at on public.push_device_tokens;
create trigger push_device_tokens_touch_updated_at before update on public.push_device_tokens for each row execute function public.touch_updated_at();

drop trigger if exists push_notification_events_touch_updated_at on public.push_notification_events;
create trigger push_notification_events_touch_updated_at before update on public.push_notification_events for each row execute function public.touch_updated_at();

alter table public.timeline_comments enable row level security;
alter table public.push_device_tokens enable row level security;
alter table public.push_notification_events enable row level security;

drop policy if exists timeline_comments_select_member on public.timeline_comments;
create policy timeline_comments_select_member on public.timeline_comments
    for select to authenticated
    using (public.is_family_member(family_id));

drop policy if exists timeline_comments_insert_member on public.timeline_comments;
create policy timeline_comments_insert_member on public.timeline_comments
    for insert to authenticated
    with check (
        public.is_family_member(family_id)
        and author_caregiver_id = public.current_caregiver_id()
    );

drop policy if exists timeline_comments_update_own on public.timeline_comments;
create policy timeline_comments_update_own on public.timeline_comments
    for update to authenticated
    using (
        public.is_family_member(family_id)
        and author_caregiver_id = public.current_caregiver_id()
    )
    with check (
        public.is_family_member(family_id)
        and author_caregiver_id = public.current_caregiver_id()
    );

drop policy if exists timeline_comments_delete_own on public.timeline_comments;
create policy timeline_comments_delete_own on public.timeline_comments
    for delete to authenticated
    using (
        public.is_family_member(family_id)
        and author_caregiver_id = public.current_caregiver_id()
    );

drop policy if exists push_device_tokens_select_own on public.push_device_tokens;
create policy push_device_tokens_select_own on public.push_device_tokens
    for select to authenticated
    using (caregiver_id = public.current_caregiver_id());

drop policy if exists push_device_tokens_insert_own on public.push_device_tokens;
create policy push_device_tokens_insert_own on public.push_device_tokens
    for insert to authenticated
    with check (
        public.is_family_member(family_id)
        and caregiver_id = public.current_caregiver_id()
    );

drop policy if exists push_device_tokens_update_own on public.push_device_tokens;
create policy push_device_tokens_update_own on public.push_device_tokens
    for update to authenticated
    using (caregiver_id = public.current_caregiver_id())
    with check (
        public.is_family_member(family_id)
        and caregiver_id = public.current_caregiver_id()
    );

drop policy if exists push_device_tokens_delete_own on public.push_device_tokens;
create policy push_device_tokens_delete_own on public.push_device_tokens
    for delete to authenticated
    using (caregiver_id = public.current_caregiver_id());

drop policy if exists push_notification_events_select_related on public.push_notification_events;
create policy push_notification_events_select_related on public.push_notification_events
    for select to authenticated
    using (
        recipient_caregiver_id = public.current_caregiver_id()
        or actor_caregiver_id = public.current_caregiver_id()
    );

drop policy if exists push_notification_events_insert_actor on public.push_notification_events;
create policy push_notification_events_insert_actor on public.push_notification_events
    for insert to authenticated
    with check (
        public.is_family_member(family_id)
        and actor_caregiver_id = public.current_caregiver_id()
    );

grant select, insert, update, delete on public.timeline_comments to authenticated;
grant select, insert, update, delete on public.push_device_tokens to authenticated;
grant select, insert on public.push_notification_events to authenticated;
grant usage, select on sequence public.timeline_comments_id_seq to authenticated;
grant usage, select on sequence public.push_device_tokens_id_seq to authenticated;
grant usage, select on sequence public.push_notification_events_id_seq to authenticated;

create or replace function public.upsert_push_device_token_checked(
    p_family_id bigint,
    p_expo_push_token text,
    p_platform text default 'unknown',
    p_device_id text default null,
    p_app_version text default null
)
returns public.push_device_tokens
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_token public.push_device_tokens%rowtype;
    v_expo_push_token text := trim(coalesce(p_expo_push_token, ''));
    v_platform text := lower(trim(coalesce(p_platform, 'unknown')));
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_expo_push_token = '' then raise exception 'Expo push token is required'; end if;
    if v_platform not in ('ios','android','web','unknown') then v_platform := 'unknown'; end if;

    insert into public.push_device_tokens(
        family_id,
        caregiver_id,
        expo_push_token,
        platform,
        device_id,
        app_version,
        enabled,
        last_seen_at
    ) values (
        p_family_id,
        v_current.id,
        v_expo_push_token,
        v_platform,
        nullif(trim(coalesce(p_device_id, '')), ''),
        nullif(trim(coalesce(p_app_version, '')), ''),
        true,
        now()
    )
    on conflict (caregiver_id, expo_push_token) do update set
        family_id = excluded.family_id,
        platform = excluded.platform,
        device_id = excluded.device_id,
        app_version = excluded.app_version,
        enabled = true,
        last_seen_at = now(),
        updated_at = now()
    returning * into v_token;

    return v_token;
end;
$$;

create or replace function public.create_timeline_comment_checked(
    p_family_id bigint,
    p_chat_message_id bigint,
    p_parent_comment_id bigint,
    p_body text
)
returns public.timeline_comments
language plpgsql
set search_path = public
as $$
declare
    v_current public.caregivers%rowtype;
    v_message public.chat_messages%rowtype;
    v_parent public.timeline_comments%rowtype;
    v_comment public.timeline_comments%rowtype;
    v_body text := trim(coalesce(p_body, ''));
    v_event_type text := 'TIMELINE_COMMENT';
    v_title text := '새 댓글이 달렸어요';
    v_recipient_id bigint;
begin
    v_current := public.current_caregiver();
    if v_current.family_id <> p_family_id then raise exception 'Family access denied'; end if;
    if v_body = '' then raise exception 'Comment body is required'; end if;

    select * into v_message
    from public.chat_messages
    where id = p_chat_message_id
      and family_id = p_family_id
    limit 1;

    if not found then raise exception 'Timeline item was not found'; end if;

    if p_parent_comment_id is not null then
        select * into v_parent
        from public.timeline_comments
        where id = p_parent_comment_id
          and family_id = p_family_id
          and chat_message_id = p_chat_message_id
        limit 1;

        if not found then raise exception 'Parent comment was not found'; end if;
        if v_parent.parent_comment_id is not null then raise exception 'Replies can only be added to a top-level comment'; end if;

        v_event_type := 'TIMELINE_REPLY';
        v_title := '새 답글이 달렸어요';
    end if;

    insert into public.timeline_comments(family_id, chat_message_id, parent_comment_id, author_caregiver_id, body)
    values (p_family_id, p_chat_message_id, p_parent_comment_id, v_current.id, v_body)
    returning * into v_comment;

    for v_recipient_id in
        select distinct recipient_id
        from (
            values
                (v_message.sender_id),
                (case when p_parent_comment_id is not null then v_parent.author_caregiver_id else null end)
        ) as recipients(recipient_id)
        where recipient_id is not null
          and recipient_id <> v_current.id
    loop
        insert into public.push_notification_events(
            family_id,
            recipient_caregiver_id,
            actor_caregiver_id,
            event_type,
            title,
            body,
            data
        ) values (
            p_family_id,
            v_recipient_id,
            v_current.id,
            v_event_type,
            v_title,
            left(format('%s: %s', v_current.name, v_body), 180),
            jsonb_build_object(
                'chatMessageId', p_chat_message_id,
                'commentId', v_comment.id,
                'parentCommentId', p_parent_comment_id,
                'route', '/timeline'
            )
        );
    end loop;

    return v_comment;
end;
$$;

revoke all on function public.upsert_push_device_token_checked(bigint, text, text, text, text) from public, anon;
revoke all on function public.create_timeline_comment_checked(bigint, bigint, bigint, text) from public, anon;

grant execute on function public.upsert_push_device_token_checked(bigint, text, text, text, text) to authenticated;
grant execute on function public.create_timeline_comment_checked(bigint, bigint, bigint, text) to authenticated;
