create table if not exists public.caregiver_legal_consents (
    id bigint generated by default as identity primary key,
    caregiver_id bigint not null references public.caregivers(id) on delete cascade,
    auth_user_id uuid not null references auth.users(id) on delete cascade,
    document_type text not null check (document_type in ('TERMS', 'PRIVACY')),
    document_version text not null,
    accepted_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (caregiver_id, document_type, document_version)
);

create index if not exists idx_caregiver_legal_consents_caregiver_accepted
    on public.caregiver_legal_consents(caregiver_id, accepted_at desc);

alter table public.caregiver_legal_consents enable row level security;

create or replace function public.record_current_caregiver_legal_consents(
    p_terms_version text,
    p_privacy_version text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_caregiver_id bigint;
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    if p_terms_version <> '2026-07-24' or p_privacy_version <> '2026-07-24' then
        raise exception 'Required legal document versions were not accepted';
    end if;

    select caregiver.id
    into v_caregiver_id
    from public.caregivers as caregiver
    where caregiver.auth_user_id = auth.uid()
    order by caregiver.updated_at desc
    limit 1;

    if v_caregiver_id is null then
        raise exception 'Current caregiver was not found';
    end if;

    insert into public.caregiver_legal_consents(
        caregiver_id,
        auth_user_id,
        document_type,
        document_version
    )
    values
        (v_caregiver_id, auth.uid(), 'TERMS', p_terms_version),
        (v_caregiver_id, auth.uid(), 'PRIVACY', p_privacy_version)
    on conflict (caregiver_id, document_type, document_version) do nothing;
end;
$$;

create or replace function public.complete_email_auth_caregiver_with_consent(
    p_invite_code text default null,
    p_caregiver_name text default null,
    p_role text default null,
    p_terms_version text default null,
    p_privacy_version text default null
)
returns table(caregiver_id bigint, family_id bigint, child_id bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    return query
    select *
    from public.complete_email_auth_caregiver(
        p_invite_code,
        p_caregiver_name,
        p_role
    );

    if p_terms_version is not null or p_privacy_version is not null then
        perform public.record_current_caregiver_legal_consents(
            p_terms_version,
            p_privacy_version
        );
    end if;
end;
$$;

create or replace function public.complete_google_oauth_caregiver_with_consent(
    p_invite_code text default null,
    p_terms_version text default null,
    p_privacy_version text default null
)
returns table(caregiver_id bigint, family_id bigint, child_id bigint)
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null then
        raise exception 'Supabase auth session is required';
    end if;

    return query
    select *
    from public.complete_google_oauth_caregiver(p_invite_code);

    if p_terms_version is not null or p_privacy_version is not null then
        perform public.record_current_caregiver_legal_consents(
            p_terms_version,
            p_privacy_version
        );
    end if;
end;
$$;

revoke all on table public.caregiver_legal_consents from public, anon, authenticated;
revoke all on function public.record_current_caregiver_legal_consents(text, text) from public, anon;
revoke all on function public.complete_email_auth_caregiver_with_consent(text, text, text, text, text) from public, anon;
revoke all on function public.complete_google_oauth_caregiver_with_consent(text, text, text) from public, anon;

grant execute on function public.complete_email_auth_caregiver_with_consent(text, text, text, text, text) to authenticated;
grant execute on function public.complete_google_oauth_caregiver_with_consent(text, text, text) to authenticated;
